# Generated by Django 4.2.7 on 2024-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True, blank=True),
            preserve_default=False,
        ),
    ]
