# Generated by Django 4.2.7 on 2023-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_point', '0003_alter_measurementpoint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementpoint',
            name='household_size',
            field=models.IntegerField(default=1),
        ),
    ]
