# Generated by Django 4.2.7 on 2023-12-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('contract', '0002_contract_measurement_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='address.address'),
            preserve_default=False,
        ),
    ]
