# Generated by Django 4.2.7 on 2023-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='household_size',
            field=models.IntegerField(default=1),
        ),
    ]
