# Generated by Django 4.2.7 on 2023-12-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_uid', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('latest_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latest_reading_date', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
            options={
                'db_table': 'measurement_point',
            },
        ),
    ]
