# Generated by Django 4.2.7 on 2023-12-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_point', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementpoint',
            name='contract',
        ),
    ]
