# Generated by Django 4.2.7 on 2024-01-04 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_point', '0004_measurementpoint_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementpoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurementpoint',
            name='meter_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
