# Generated by Django 4.2.7 on 2024-01-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_point', '0006_alter_measurementpoint_household_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('first_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField(editable=False)),
                ('year', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement_point.measurementpoint')),
            ],
            options={
                'db_table': 'measurement_reading',
                'unique_together': {('measurement_point', 'year', 'month')},
            },
        ),
    ]
