# Generated by Django 4.2.7 on 2023-12-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_point', '0002_remove_measurementpoint_contract'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='measurement_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='measurement_point.measurementpoint'),
        ),
    ]
