# Generated by Django 4.2.7 on 2023-12-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tariff', '0001_initial'),
        ('contract', '0003_contract_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tariff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='energy_tariff.energytariff'),
            preserve_default=False,
        ),
    ]
