# Generated by Django 4.2.7 on 2024-01-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_contract_household_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='address',
        ),
    ]
