# Generated by Django 4.2.7 on 2024-01-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('contract', '0008_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='address.address'),
        ),
    ]
