# Generated by Django 4.2.7 on 2024-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_measurement_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
            preserve_default=False,
        ),
    ]
