# Generated by Django 4.2.7 on 2024-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='subject',
            new_name='action',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='second_token',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
