# Generated by Django 4.2.7 on 2024-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0002_rename_subject_emailconfirmation_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
