# Generated by Django 4.2.7 on 2024-01-05 18:39

from django.db import migrations, models
import email_confirmation.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0003_emailconfirmation_claimed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='expiration_data',
            field=models.DateTimeField(default=email_confirmation.models.seven_days_from_now),
        ),
    ]
