# Generated by Django 4.2.7 on 2023-11-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
