# Generated by Django 4.2.7 on 2023-11-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_delete_post_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
