# Generated by Django 4.2.7 on 2023-12-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
